### ISSUE TITLE
Integrate JSON decoding

### ISSUE THREAD

**Issue by marcushultman** [tabbies/vue-reactive-cookie#1]
Instead of having the user do `JSON.parse` on members of `$cookies`, several solutions can be made to facilitating json decoding:
- Provide a `$cookiesJSON` (bad, decodes everything, always)
- Provide a plugin option for using `Cookies.getJSON()` (as above, but opt-in)
- Use a converter ([js-cookie#converters](https://github.com/js-cookie/js-cookie#converters)), together with any of the above.
- Provide a custom `options`-field in `$setCookie` (`{json: true}`?) that will put the cookie in a whitelist that can be used to filter which cookies will be used in a converter ([js-cookie#converters](https://github.com/js-cookie/js-cookie#converters)).

I can happily make a pull request if this is relevant.

**Comment by pbelyaev** [comment]
Hello, @marcushultman. Thank you for your contribution. I like this idea and I'll try to implement one of suggested solutions. If somehow I couldn't make it, please feel free to implement it yourself I'll gladly merge it.

**Comment by pbelyaev** [comment]
@marcushultman please, take a look at referenced pull request above. I'll update the README.md file later and then merge the pull request.

**Comment by pbelyaev** [comment]
Done
